### ISSUE TITLE
webPage sample and hollowed sphere demo part

### ISSUE THREAD

**Issue by yvanblanchard** [GabrielMusat/react-gcode-viewer#22]
Hello,

Thank you for your great web app.

Coudl it be possible to have a simple HTML webpage, embedding your viewer, as an example ? (running on web server, even local)
I am not so skilled in JS/HTML.

Moreover, could you also please share the sphere (mesh) demo files (stl and gcode), as showed in your GIF ?

Thank you.

**Comment by yvanblanchard** [comment]
Ok, I found the sample gcode myself:
https://storage.googleapis.com/ucloud-v3/61575ddb9d8a176950431398.gcode
If you could share the corresponding STEP or STL file, it would be very nice.
Thanks.

**Comment by gabotechs** [comment]
sure, this is the STL that was used to generate the GCode that is shown in the demo https://storage.googleapis.com/ucloud-v3/61575ca49d8a1777fa431395.stl.

About embedding this library into a simple HTML webpage... I don't know how to do that. This is just a [React](https://reactjs.org/) component library, so it assumes that you are going to use React for building the a web application.
