### ISSUE TITLE
Problem loading Gcode from Octoprint

### ISSUE THREAD

**Issue by AntoineFra** [GabrielMusat/react-gcode-viewer#4]
Hi,

I'm currently trying to make my own octoprint GUI and I want to use your gcode viewer. But when it comes to loading a gcode it doesn't work with a file hosted from octoprint. I use this url : [http://my-ip:my_port/downloads/files/local/CE3PRO_calicat.gcode](url) and I get a 403 forbidden on my request because GCodeViewer isn't logged and accepted by octoprint.
Is there another way of loading Gcode besides a url ?

**Comment by gabotechs** [comment]
You have two options: 
- You can configure the `GCodeViewer` to use custom headers in the http request, something like this:
```ts
<GCodeViewer
    ...
    reqOptions={{headers: {'X-Api-Key': 'your-api-key'}}}
/>
```
[here](https://docs.octoprint.org/en/master/api/general.html#authorization) are the octoprint's docs that show you how to authenticate with their API

- you can also pass a local file like this
```ts
<GCodeViewer
    ...
    url={URL.createObjectURL(file)}
/>
```
[here](https://github.com/gabotechs/react-gcode-viewer/blob/master/.storybook/stories/FromFile.stories.tsx) is an example on how to use a local `File` object

**Comment by AntoineFra** [comment]
Thanks everything is working now. But why not add this to the documentation ?

**Comment by gabotechs** [comment]
The `reqOptions` are actually already in the README.md documentation. The usage of a local `File` object is only documented as one of the storybook examples, but it looks like a common question, so you are right, I will add it soon to the README.md.
