### ISSUE TITLE
Camera Initial Position

### ISSUE THREAD

**Issue by rafafontanacrespo** [GabrielMusat/react-gcode-viewer#5]
Hi, Is there a way to set the camera initial position from a top view of the grid? I check within the different props, and does not seem an option. Thanks in advance

**Comment by gabotechs** [comment]
Right now the initial camera setup is fixed, but it is an interesting feature, I will add it soon.

**Comment by gabotechs** [comment]
Version 2.2.0:

You can now set the `cameraInitialPosition` in the `GCodeViewer` to override the initial camera position. The position is given in geographical coordinates, so if you want a top view of the grid this will look something like:
```tsx
<GCodeViewer
    ...
    cameraInitialPosition={{
        latitude: Math.PI / 2,
        longitude: 0,
        distance: 300 // in mm
    }}
/>
```
A front view of the scene will look like this:
```tsx
<GCodeViewer
    ...
    cameraInitialPosition={{
        latitude: 0,
        longitude: 0,
        distance: 300 // in mm
    }}
/>
```
